### ISSUE TITLE
Support for shell, terminal and editor version detection?

### ISSUE THREAD

**Issue by CarterLi** [LivacoNew/CrabFetch#13]

**Comment by LivacoNew** [comment]
Added to my to-do list, just need to figure out a way to do this that works for every software that doesn't completely obliterate performance.

**Comment by LivacoNew** [comment]
Why was this closed? This is planned to be done, just that I have other stuff I want to do first as I research this more.

**Comment by LivacoNew** [comment]
![image](https://github.com/user-attachments/assets/cbe50467-7032-446a-bb75-419fc3085420)
Just showing that yes this is progressing, very very basic (& slow) version detection on a local branch. Got to do a few more things before I push it up (including removing said slowness), but it's got an impl.

**Comment by LivacoNew** [comment]
Added in [commit e4ea07f](https://github.com/LivacoNew/CrabFetch/commit/e4ea07fd5b53db7b42639b1692668bdb02985da4) :)
