### ISSUE TITLE
Intel CPU reports Frequency wrong (Asahi Linux Support)

### ISSUE THREAD

**Issue by CarterLi** [LivacoNew/CrabFetch#18]
It's an actual Linux distro. Don't know if you care it.

![image](https://github.com/user-attachments/assets/defc9dcb-a47b-4568-85e3-1cfa50010266)

Worth noting that the CPU frequency was wrong too. Crabfetch reports the frequency of efficiency cores instead of the freq of performance cores. Also you should remove `0 (flatpak)`

While fastfetch reports ( with my modified config )

![image](https://github.com/user-attachments/assets/0a017c85-2754-4c2d-b917-54b892ab584c)

**Comment by CarterLi** [comment]
Why do you use `1 KB = 1000 B` instead of `1 KiB = 1024 B`?

**Comment by LivacoNew** [comment]
> It's an actual Linux distro. Don't know if you care it.

I don't own a Macbook, and most sources I can find say you can't visualize Asahi as it expects M1 hardware. For Asahi, it's not a case of I won't, it's a case of _I can't_.

> Why do you use 1 KB = 1000 B instead of 1 KiB = 1024 B?

Look in your config file.
![image](https://github.com/user-attachments/assets/967f1fa5-8a2d-457b-b8e2-42c90f4cb19e)

**Comment by CarterLi** [comment]
You should fix the CPU freq issue at least. Intel CPUs use P/E cores too.

**Comment by LivacoNew** [comment]
> You should fix the CPU freq issue at least. Intel CPUs use P/E cores too.

Once I can live boot into a Intel CPU I shall.

**Comment by CarterLi** [comment]
I know what's wrong with crabfetch. fastfetch had this issue too.

You should enumerate all CPU cores, instead of assuming the first core is P core.

**Comment by LivacoNew** [comment]
> I know what's wrong with crabfetch. fastfetch had this issue too.
> 
> You should enumerate all CPU cores, instead of assuming the first core is P core.

Will do this and commit tonight (slash this morning as it's 5am for me). Expecting performance to take a shit but needs to be done ig.

**Comment by LivacoNew** [comment]
Mind testing if the patch works?
[maxfreq_intel.patch.txt](https://github.com/user-attachments/files/16188797/maxfreq_intel.patch.txt)

**Comment by CarterLi** [comment]
yeah
