### ISSUE TITLE
Wrong display name and resolution

### ISSUE THREAD

**Issue by CarterLi** [LivacoNew/CrabFetch#21]
![image](https://github.com/user-attachments/assets/595377a6-20b8-4d70-9982-723f79e5c2e0)

Display (BOE eDP-2-0x09F9) > 1280x720 @ 240Hz (eDP-2)

My display configuration

![image](https://github.com/user-attachments/assets/ce58c1cd-2f9a-4121-b24e-e8043f43538e)

You should print either 2560x1440 or 1706x960. The name `BOE eDP-2-0x09F9` seems strange too.

**Comment by LivacoNew** [comment]
On Wayland it grabs the make/model from the compositor, so I'm guessing KDE is returning something wonky. Downloading Manjaro as a "close enough" to test this as my EndeavourOS live boot only has X11

If that's true I can just check for KDE and return the EDID values instead.

**Comment by LivacoNew** [comment]
Seems to just be affecting laptops, I'm guessing the internal screens mean most manufacturers don't bother with the normal way or something? Either way there's definitely some way to recover it, as my laptop's screen comes out as `AU Optronics 0x459D` whereas the actual panel name is `AUO459D` so it's damn close. Will need to look at this tomorrow as I've ran out of time for today however.

Dedicated monitors _should_ remain unaffected.

**Comment by CarterLi** [comment]
Since you are developing a neofetch like tool, why not install these DEs in your local machine, instead of testing it in the shitty live CD?

**Comment by LivacoNew** [comment]
> Since you are developing a neofetch like tool, why not install these DEs in your local machine, instead of testing it in the shitty live CD?

Would prefer not to clutter my drive with random DE's I'll never use for a project that, being realistic only I seem to use on a daily basis. If you take a look at the README showcases, you'll see that my storage is already quite tight.

Maybe will sacrifice my laptop's storage a bit once I'm not traveling as much as I am right now, but that's gonna have to be a bit later.



> BTW on X11 crab reports `Unknown Unknown` and `N/AHz`, which is unacceptable.

No refresh rate as I simply couldn't find a way to get it from X11, if you know what to query I'm happy to add it.

As for the make/model, these are fetched from your EDID display descriptors so take a look at if it's set (my laptop doesn't have the model set in EDID for example). Tbf I should likely backup to the ID Product Code but I'll have to investigate that later as I am busy for the first half of today.

**Comment by LivacoNew** [comment]
Also just had a thought for your incorrect resolution; try setting your scale to 100% and seeing what it comes out as. If it ends up being correct, that tells me where I need to look later today instead of me fiddling with it myself.

**Comment by CarterLi** [comment]
> No refresh rate as I simply couldn't find a way to get it from X11

So why not hide it from the output, instead of displaying a meaningless and ugly N/AHz? Same as GPU VMEM size.

**Comment by CarterLi** [comment]
> As for the make/model, these are fetched from your EDID display descriptors so take a look at if it's set (my laptop doesn't have the model set in EDID for example).

They are required field. All EDID data should contain them, including laptops.

The marketing name, however, is not required and most laptop builtin monitors dont have it.

**Comment by CarterLi** [comment]
> Also just had a thought for your incorrect resolution; try setting your scale to 100% and seeing what it comes out as. If it ends up being correct, that tells me where I need to look later today instead of me fiddling with it myself.

You need to look at fractional scale factor. To reproduce this issue, you simply set the scale factor to 1.5

Fastfetch had all these issues. It took me more than 6 months to find a solution. If you think you are smarter, do it.

**Comment by CarterLi** [comment]
> try setting your scale to 100% and seeing what it comes out as. If it ends up being correct, that tells me where I need to look later today instead of me fiddling with it myself.

You need to look at fractional scale factor. To reproduce this issue, you simply set the scale factor to 1.5

**Comment by LivacoNew** [comment]
> > No refresh rate as I simply couldn't find a way to get it from X11
> 
> So why not hide it from the output, instead of displaying a meaningless and ugly N/AHz? Same as GPU VMEM size.

If you take a look at the format;

![image](https://github.com/user-attachments/assets/d468991c-1536-4c51-b074-989f91b667ff)

I would rather have it be an obvious `Display (Unknown Unknown)` where that placeholder can't be found, opposed to `Display ()` where it could be confusing to a user what's the issue.



> > As for the make/model, these are fetched from your EDID display descriptors so take a look at if it's set (my laptop doesn't have the model set in EDID for example).
> 
> They are both required fields. All EDID data should contain them, including laptops'.
> 
> The marketing name, however, is not required and most laptop builtin monitors dont have it.
> 
> It was because you failed to find the EDID data.

I only check the the marketing name from the display descriptors which ye I now see is incorrect, hence my comment of "Tbf I should likely backup to the ID Product Code"



> > try setting your scale to 100% and seeing what it comes out as. If it ends up being correct, that tells me where I need to look later today instead of me fiddling with it myself.
> 
> You need to look at fractional scale factor. To reproduce this issue, you simply set the scale factor to 1.5

In that case I'm not sure I can fix this, as from what I can tell my wayland client library `wayland_client` knows about the the protocol but still returns the scale to me remains as an `i32` with no obvious way to get the scale elsewhere?
![image](https://github.com/user-attachments/assets/27dc8927-42d6-49ee-90c8-e4b89f49d032)
![image](https://github.com/user-attachments/assets/6902dd24-76a0-461d-9f98-e41fdddd6286)

When setting KDE's scale to 150% it returns `2` to me, which is what gets divided. Likely temporary action I can take is simply to add a config option to disable scaling the display.

**Comment by CarterLi** [comment]
fastfetch can detect it; no way you can't

**Comment by LivacoNew** [comment]
Wrong model/make should be fixed in the next commit I do in a few secs swapping wayland to use edid and using the product id if the marketing name is not available. Fractional scaling will not be fixed. As previously said, the library I'm using seemingly doesn't support it. 
I took a look at FastFetch's code, your interacting with the wayland library directly and thus can do what you want, something I can't really do because of Rust. Unless I can upstream the work to the wayland-client bindings (which I have no idea how to do), then it's out the window unfortunately. The only other way I can see to do it is to use zxdg output objects, which are only unstable in the wayland-client crate and thus also out the window.
