### ISSUE TITLE
Wrong shell and terminal detection

### ISSUE THREAD

**Issue by CarterLi** [LivacoNew/CrabFetch#23]
`sudo -E crabfetch`. `sudo` will be detected as shell and terminal.

![image](https://github.com/user-attachments/assets/aead9951-1a09-4833-b5ae-aab2dd272d98)

Run another terminal inside one terminal. For example, run kitty inside konsole

![image](https://github.com/user-attachments/assets/ec588127-a5d0-4086-9e6b-155792135de6)

Irrelevant: the display name is wrong. Should be `BOE09F9`

**Comment by CarterLi** [comment]
If I compile crab with `cargo b --all-features`, shell detection will not work

**Comment by LivacoNew** [comment]
Both your issues are likely caused with `$SHLVL` being funny, will look into why.

> If I compile crab with `cargo b --all-features`, shell detection will not work

Your compiling with `android`, which detects shell in a different way, don't do this.

**Comment by LivacoNew** [comment]
> Irrelevant: the display name is wrong. Should be BOE09F9

Send me a sample of your EDID file so I can play with the data myself please. Will be in `/sys/class/drm/{card/drm name of display}/edid`

**Comment by LivacoNew** [comment]
Shell/Terminal issues are just convincing me to rewrite how they detect, as `$SHLVL` is way more unreliable than I thought it was. Likely easiest way is to simply keep a list of shells/terminals and to keep going up parent processes until it finds the first instance of each.

I can work around the sudo problem by simply checking for it and adding +2 to the shell level, but terminal issue is a bit more complicated. Will likely take a little bit to fix this, sorry.
