### ISSUE TITLE
Nushell is not detected

### ISSUE THREAD

**Issue by ralencode** [LivacoNew/CrabFetch#41]
**What module does this affect?**
Shell

**What hardware/software isn't being detected right?**
/usr/bin/nu (nushell). echo $env.SHELL works correctly, it's /usr/bin/nu

**Does detection work a little, or is it completely broken?**
it can detect bash when launched from bash
![image](https://github.com/user-attachments/assets/1dfc10ba-8754-4247-a681-9104bfac514b)

**Comment by LivacoNew** [comment]
Fixed :) 
![image](https://github.com/user-attachments/assets/43b789af-878d-4e4d-9358-913df64df7f9)
